# Cloudinary get these from your Cloudinary dashboard
cloud_name=YOUR_CLOUD_NAME_HERE
api_key=YOUR_API_KEY_HERE
api_secret=YOUR_API_SECRET_HERE

# Database your local PostgreSQL instance
db.url=jdbc:postgresql://localhost:5432/YOUR_DB_NAME_HERE
db.user=YOUR_DB_USER_HERE
db.password=YOUR_DB_PASSWORD_HERE

# Hibernate set to true during development to see SQL in the console, false otherwise
hibernate.show_sql=true

#mailing credentials
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=your_smtp_user
mail.smtp.password=your_app_password
mail.smtp.auth=true
mail.smtp.starttls.enable=true

# SITE KEY
recaptcha.site_key=PASTE_YOUR_SITE_KEY_HERE

# SECRET KEY
recaptcha.secret_key=PASTE_YOUR_SECRET_KEY_HERE